name: movie_night
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4
  provider:
  shared_preferences: ^2.1.1
  google_fonts: ^4.0.4
  device_info_plus: ^11.0.0
  flutter_dotenv: ^5.0.2
  android_id:
  platform_device_id: ^1.0.1
  lottie: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:
  flutter_launcher_icons:
  flutter_native_splash:

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"

flutter_native_splash:
  color: "#000000"
  background_color: "#000000"
  image: assets/images/splash.jpg
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/splash.jpg
    - .env
