name: movie_night
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4
  provider:
  shared_preferences: ^2.1.1
  google_fonts: ^4.0.4
  device_info_plus: ^11.0.0
  flutter_dotenv: ^5.0.2
  android_id:
  platform_device_id: ^1.0.1
  lottie: ^2.2.0
  flutter_card_swiper: ^7.0.2
  swipe_cards: ^2.0.0+1
  flutter_swiper_view: ^1.1.8
  flutter_launcher_icons: ^0.14.1
  flutter_native_splash: ^2.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.jpg"

flutter_native_splash:
  image: assets/images/splash.jpg
  color: "#000000"
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/splash.jpg
    - assets/images/icon.png
    - assets/images/background.jpg
    - .env
