name: movie_night
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  http:
  provider:
  shared_preferences:
  google_fonts:
  device_info_plus: ^11.0.0
  flutter_dotenv:
  android_id:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:
  flutter_launcher_icons:
  flutter_native_splash:

flutter:
  uses-material-design: true
  assets:
    - assets/splash.jpg
    - .env
